---
- name: Install Docker
  hosts: all
  gather_facts: true
  roles:
    - { role: ../roles/docker }

- name: Setup Komodo
  hosts: all
  roles:
    - { role: ../roles/komodo/core }
    - { role: ../roles/komodo/periphery }
